### PR TITLE
Return proper error message when recovering iteration / setup errors

### PR DESCRIPTION
**Pull request by naag**

### CODE REVIEW

**Review by markhowardform3 — CHANGES_REQUESTED** [review]
This doesn't look right. When the type assertion fails, err is set to the zero value of error.

**Comment by naag** [comment]
When the type assertion fails, we report the original value returned by `recover()` using a `%v` format string. I've added some unit tests to this. The tests `TestReports...` show the behavior of the recovery function.

**Comment by naag** [comment]
When a `panic("string")` happens, we'll end up logging `"panic in iteration 0: string"`. With a `panic(fmt.Errorf("boom"))`, we end up logging `iteration 0 failed due to: boom`.

**Review by markhowardform3 — DISMISSED** [review]

**Comment by markhowardform3** [comment]
> This doesn't look right. When the type assertion fails, err is set to the zero value of error.

Think I must be colour blind today - I'm sure it was the other way round when I looked at the PR earlier.

**Review by markhowardform3 — APPROVED** [review]

**Pull request merged**
