### PR TITLE
Config file mode

### PR DESCRIPTION
**Pull request by laurentiu-marcut**
Create a new mode which will accept a yaml config file in order to run complex executions and be able to combine multiple existing modes and be more clear on the command syntax.

- [x] Add new mode `f1 run/chart <filename>`.
- [x] Combine existing trigger modes: constant, staged, gaussian, users.
- [x] Use default values for every stage value. If any value is not provided, the program will fail.
- [x] The program will finish once all the stages finish their execution (sequentially) or any of the limits will be reached (max-duration, max-iterations).
- [x] When start-stage field is provided, in case of restart, the program will skip the stages which were executed.
- [x] Create a new trigger "ramp"  as a simpler alternative to the existing staged and incorporate it in the file mode as well.

### CODE REVIEW

**Review by andykuszyk — APPROVED** [review]

**Comment by andykuszyk** [comment]
Approved, but looks like there was a test failure in the PR build?

**Comment by laurentiu-marcut** [comment]
> Approved, but looks like there was a test failure in the PR build?

**Comment by laurentiu-marcut** [comment]
> Approved, but looks like there was a test failure in the PR build?

I'm having a look as one of the tests seems to be flaky.

**Review by andykuszyk — APPROVED** [review]
Looks good to me. The main thing I was wondering about was removing the go routine in `NewIterationWorker`, but it seems that this function is only called from `test_runner.go`, which runs it in its own go routine anyway, so there's no need for an inner go routine :+1:

**Comment by laurentiu-marcut** [comment]
> Looks good to me. The main thing I was wondering about was removing the go routine in `NewIterationWorker`, but it seems that this function is only called from `test_runner.go`, which runs it in its own go routine anyway, so there's no need for an inner go routine 👍

Yeah, that was the main reason I remove it. Also its more consistent with the user worker.

**Pull request merged**
