### PR TITLE
Explain how to get the library

### PR DESCRIPTION
**Pull request by ramonberrutti-f3**
Explain how to get the library to avoid getting old version (1.0.0)

### CODE REVIEW

**Review by andykuszyk-form3 — APPROVED** [review]

**Comment by andykuszyk-form3** [comment]
Closing and re-opening to try to re-trigger Travis build.

**Comment by ramonberrutti-f3** [comment]
@andykuszyk-form3 we need someone from code-owner approve first.

**Comment by andykuszyk-form3** [comment]
> @andykuszyk-form3 we need someone from code-owner approve first.

I'm able to approve this PR, but the branch build in Travis is a required status check. I don't think this build is running, because this is a PR from a fork.

I'll remove this required status check, and then we'll be able to merge this PR.

**Comment by andykuszyk-form3** [comment]
@ramonberrutti-f3 I've just spotted that you're a Form3 employee :slightly_smiling_face: 

You could also push directly to this repo, rather than forking, which would also solve the problem I think.

**Pull request closed without merging**
